### ISSUE TITLE
训练数据问题

### ISSUE THREAD

**Issue by lonleyodd** [lhaippp/GyroFlow-PyTorch#4]
按照作者给的数据以及训练参数，我将data_dir改为数据本地存放地址，运行时报错没有‘frames.npy'文件，请问这个frames.npy是哪个

**Comment by lhaippp** [comment]
Hi, 
sorry for the bug,  try to replace https://github.com/lhaippp/GyroFlow-PyTorch/blob/bd1c1f4e780f1a5e5304044193124af5d7872e17/model/data_loader.py#L236:
```
# replace the following code
ds = ConcatDataset([
    FrameDataset(frame_path,
                 input_transform=input_transform,
                 spatial_transform=spatial_transform,
                 with_gt_flow=None,
                 evaluate_with_whole_img=None,
                 weather_transform=None),
    FrameDatasetV2(input_transform=input_transform, spatial_transform=spatial_transform)
])
```
```
ds = FrameDatasetV2(input_transform=input_transform, spatial_transform=spatial_transform)
```
we will fix it soon.

**Comment by lonleyodd** [comment]
thanks for your support, i will try it later .by the way,from the Megengine version,  I understand  data processing pipeline, maybe can fix it

**Comment by lhaippp** [comment]
Great, btw, we will update the dataset&code in this week, maybe you can try it
