### ISSUE TITLE
Access Gyro Reading

### ISSUE THREAD

**Issue by Fcsalvagnini** [lhaippp/GyroFlow-PyTorch#5]
How can I have access to Gyro reading? Instead of only the gyro_homo (gyro_homo.npy).

I have downloaded the GHOF_Train, and want access to the gyro readings that generates the gyro_home. Could you please share with me?

Thanks.

**Comment by lhaippp** [comment]
Hi,

The processing of raw gyro readings (e.g, angular velocities in row-pitch-yaw) is a bit complicated and it might require certain bussiness permission.

Furthermore, could you tell me the purpose of your use of a raw gyroscope? This may help me assist you better.

**Comment by Fcsalvagnini** [comment]
Of course.

I'm developing a demo based on your proposal to test on mobile devices. Hence, I'm implementing gyro reading from HAL (as you do) and trying to generate the global motion from it.

Having your ground-truth and input data will be great for validation!

**Comment by lhaippp** [comment]
Ok, got it.

I think we are capable for providing you some help in 2 ways:

   1. We've develped an application based on gyroscope readings to do video stabilization which will be released soonly (check the progress there [gyro-dvs](https://github.com/lhaippp/gyro-video-stabilization)), there will be some raw data available
   2. We will try to release the gyro readings of part of the benchmark (i.e., GHOF-Clean) as you might need the optical flow ground-truth, we will try it in the next 5 days.

Is it okay for you?

**Comment by Fcsalvagnini** [comment]
Yeah, for sure.

Thank you!

**Comment by lhaippp** [comment]
Hi Fcsalvagnini,

the repo [https://github.com/lhaippp/gyro-video-stabilization](https://github.com/lhaippp/gyro-video-stabilization) is updated,

We provide a demo there to illustrate the processing of gyro readings to homography and perform image alignment,

Furthermore, I'm sry that the update of GHOF might be a little bit delay

Haipeng

**Comment by Fcsalvagnini** [comment]
Ty Ihaippp!
