### ISSUE TITLE
unflowloss and GyroflowLoss

### ISSUE THREAD

**Issue by lovean1** [lhaippp/GyroFlow-PyTorch#7]
unflowloss and GyroflowLoss这两种有什么区别吗？看上去GyroflowLoss把陀螺仪场拿来算Loss了，但是计算量也增加了，这两个Loss哪个的结果好一些呢。

**Comment by lhaippp** [comment]
> unflowloss and GyroflowLoss这两种有什么区别吗？看上去GyroflowLoss把陀螺仪场拿来算Loss了，但是计算量也增加了，这两个Loss哪个的结果好一些呢。

plz use unflowloss. (GyroflowLoss is just an non-work experiment)

**Comment by lovean1** [comment]
thank you for your reply！
